### ISSUE TITLE
Embedded e-signing problem

### ISSUE THREAD

**Issue by perffy** [SignRequest/signrequest-php-client#11]
Hi guys,

I am facing problems to implement the Embedded e-signing of SignRequest.

Till now I have created a new Document from URL and I have set an Embed URL, but I don't know how to proceed to be redirected to a new window for the signing ceremony and after that to be redirected to the embed URL?

I will appreciate your help

P.S can I set an Embed URL on the localhost or do I need to run everything on my server?

**Comment by michi88** [comment]
Yes, you will want to run that on your server as you need to redirect the user on your website to that unique url (that is the signing ceremony). You can also set the `redirect_url` to a page where you want to redirect the signer to after completing the signature.

Alternatively, if you're looking for a more simple solution without needing server side document creation, you can create a SignRequest template and have users sign that. see: https://help.signrequest.com/hc/en-us/articles/360005105393-How-to-add-a-form-to-your-website-

If you have any more questions please contact tech support here: https://help.signrequest.com/hc/en-us/requests/new

Thanks!

**Comment by perffy** [comment]
Ok, but i have used the setEmbedUrlUserId() method, so i thought that this url is used for redirection. What is the purpose of setEmbedUrlUserId?

**Comment by michi88** [comment]
When you set that ID the `embed_url` field of the signer object is populated (it's in the response). You can redirect your signer to that url. See: https://signrequest.com/api/v1/docs/#section/Additional-signing-methods/Embed-url

**Comment by perffy** [comment]
Ok, that works. Now I have two questions more:

1) by using setEmbedUrlUserId() I am setting the userId of the signer in my application, am I?

2) I have been redirected to the redirect_url on my website, but how can I get the signed document? Is there any response returned, because by print_r($_REQUEST) I don't get anything?

Thank you :)

**Comment by michi88** [comment]
1. correct
2. you will need to listen for callback events (create a endpoint on your website where SignRequest can send the events to):  https://signrequest.com/api/v1/docs/#section/Events/Events-callback You can also just download the document from the SignRequest interface.
